"""Basins for HydroGym: a synthetic one for offline work, and real gauged basins from the Archive.

A :class:`Basin` is one gauged catchment ready for rainfall-runoff work: daily
precipitation, PET and observed streamflow, all in mm/d, plus the metadata
(area, coordinates, record) and a chronological split into a calibration and
a validation period. :func:`synthetic_basin` makes one from GR4J itself with
known parameters (so tests and notebooks run with no network); :func:`load_basin`
builds one from the Archive (discharge bundle, catchment area from the agency
or BasinATLAS) with Open-Meteo forcing at the gauge point, the same recipe as
the Caravan exporter, cached locally so repeated episodes cost nothing.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

COLUMNS = ("precip", "pet", "q_obs")  # mm/d
DEFAULT_SPLIT = 0.65  # first 65 % of the record calibrates, the rest validates
MIN_DAYS = 365 * 3


@dataclass
class Basin:
    """One gauged catchment: daily forcing + observed streamflow (mm/d) and a chronological split."""

    id: str
    name: str
    frame: pd.DataFrame  # DatetimeIndex, columns precip, pet, q_obs (mm/d); q_obs may hold NaN
    area_km2: float | None = None
    latitude: float | None = None
    longitude: float | None = None
    source: str | None = None
    station_id: str | None = None
    split_date: pd.Timestamp | None = None
    meta: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        f = self.frame
        if not isinstance(f.index, pd.DatetimeIndex):
            raise TypeError("Basin.frame needs a DatetimeIndex")
        missing = [c for c in COLUMNS if c not in f.columns]
        if missing:
            raise ValueError(f"Basin.frame lacks columns {missing}")
        if len(f) < MIN_DAYS:
            raise ValueError(f"Basin needs at least {MIN_DAYS} days, got {len(f)}")
        f = f.sort_index()
        f = f[~f.index.duplicated(keep="first")]
        full = pd.date_range(f.index.min(), f.index.max(), freq="D")
        f = f.reindex(full)
        f["precip"] = f["precip"].fillna(0.0).clip(lower=0.0)
        f["pet"] = f["pet"].ffill().bfill().fillna(0.0).clip(lower=0.0)
        self.frame = f
        if self.split_date is None:
            self.split_date = f.index[int(len(f) * DEFAULT_SPLIT)]
        self.split_date = pd.Timestamp(self.split_date)

    # ── periods ──────────────────────────────────────────────────────────
    @property
    def calibration(self) -> pd.DataFrame:
        return self.frame.loc[: self.split_date - pd.Timedelta(days=1)]

    @property
    def validation(self) -> pd.DataFrame:
        return self.frame.loc[self.split_date:]

    @property
    def n_years(self) -> float:
        return round(len(self.frame) / 365.25, 1)

    def summary(self) -> dict[str, Any]:
        cal = self.calibration
        q = cal["q_obs"].dropna()
        p, e = cal["precip"], cal["pet"]
        return {
            "id": self.id, "name": self.name, "area_km2": self.area_km2, "n_years": self.n_years,
            "start": self.frame.index.min().date().isoformat(), "end": self.frame.index.max().date().isoformat(),
            "split_date": self.split_date.date().isoformat(),
            "mean_precip_mm_d": round(float(p.mean()), 3), "mean_pet_mm_d": round(float(e.mean()), 3),
            "mean_q_mm_d": round(float(q.mean()), 3) if len(q) else None,
            "runoff_ratio": round(float(q.mean() / p.mean()), 3) if len(q) and p.mean() > 0 else None,
            "aridity": round(float(e.mean() / p.mean()), 3) if p.mean() > 0 else None,
            "q_missing_fraction": round(float(cal["q_obs"].isna().mean()), 3),
        }


# ── synthetic ────────────────────────────────────────────────────────────


def synthetic_basin(seed: int = 0, *, years: int = 12, params: dict[str, float] | None = None,
                    noise: float = 0.15, name: str | None = None) -> Basin:
    """A basin generated by GR4J itself: seasonal rain (Markov wet/dry days, gamma depths), sinusoidal PET,
    the truth parameters in ``meta["true_params"]``, and lognormal noise on the observed flow.

    Reproducible for a seed, no network. Handy for tests, notebooks and sanity checks of an agent
    (a good agent gets close to the truth NSE, which is also stored in ``meta``).
    """
    from aquascope.models.rainfall_runoff import GR4J

    rng = np.random.default_rng(seed)
    idx = pd.date_range("2000-01-01", periods=365 * years, freq="D")
    doy = idx.dayofyear.to_numpy()
    season = 0.5 + 0.5 * np.sin(2 * np.pi * (doy - 30) / 365.25)  # wetter in the first months
    wet = np.zeros(len(idx), dtype=bool)
    p_wet = 0.25 + 0.35 * season
    for i in range(len(idx)):
        prev = wet[i - 1] if i else False
        wet[i] = rng.random() < (p_wet[i] + (0.35 if prev else -0.1))
    precip = np.where(wet, rng.gamma(shape=0.9, scale=6.0 + 4.0 * season), 0.0)
    pet = 1.2 + 2.2 * (0.5 - 0.5 * np.cos(2 * np.pi * (doy - 15) / 365.25)) + rng.normal(0, 0.15, len(idx))
    pet = np.clip(pet, 0.1, None)
    truth = dict(params or {"X1": 320.0, "X2": -0.8, "X3": 70.0, "X4": 2.1})
    model = GR4J(**{k.lower(): v for k, v in truth.items()})
    p_s, e_s = pd.Series(precip, index=idx), pd.Series(pet, index=idx)
    q_true = model.simulate(p_s, e_s, warmup_days=0).streamflow
    q_obs = q_true * np.exp(rng.normal(0, noise, len(idx))) if noise > 0 else q_true.copy()
    frame = pd.DataFrame({"precip": precip, "pet": pet, "q_obs": q_obs.to_numpy(), "q_true": q_true.to_numpy()},
                         index=idx)
    return Basin(id=f"synthetic-{seed}", name=name or f"Synthetic basin {seed}", frame=frame, area_km2=100.0,
                 meta={"true_params": truth, "noise": noise, "seed": seed})


# ── real basins from the Archive ─────────────────────────────────────────


def _cache_dir(cache_dir: str | Path | None) -> Path:
    if cache_dir is not None:
        return Path(cache_dir)
    from aquascope.archive.catalog import cache_dir as archive_cache

    return archive_cache() / "gym"


def suggest_basins(n: int = 10, *, sources: list[str] | None = None, min_years: float = 15.0,
                   max_snow_pct: float | None = 20.0, signatures: pd.DataFrame | None = None,
                   catchments: pd.DataFrame | None = None) -> list[dict[str, Any]]:
    """Gauged basins that make good gym tasks: long archived discharge, an agency catchment area, perennial flow,
    a plausible runoff ratio, and (by default) little snow, since GR4J has no snow routine here. Reads
    ``basins/station_signatures.parquet`` (and ``station_catchments.parquet`` for the snow cover) from the Archive.
    """
    from aquascope.archive.regionalize import load_station_signatures

    sig = signatures if signatures is not None else load_station_signatures()
    if sig.empty:
        return []
    m = (sig["n_years"] >= min_years) & (sig["zero_flow_fraction"].fillna(0) < 0.01)
    if "runoff_ratio" in sig.columns:
        rr = sig["runoff_ratio"]
        m &= rr.isna() | ((rr > 0.05) & (rr < 1.2))
    if sources:
        m &= sig["source"].isin(sources)
    cand = sig[m].copy()
    if max_snow_pct is not None:
        try:
            if catchments is None:
                from aquascope.archive.similar import load_station_catchments

                catchments = load_station_catchments()
            snow = catchments[["source", "station_id", "snow_cover_pct"]].drop_duplicates(["source", "station_id"])
            cand = cand.merge(snow, on=["source", "station_id"], how="left")
            cand = cand[cand["snow_cover_pct"].isna() | (cand["snow_cover_pct"] <= max_snow_pct)]
        except Exception as exc:  # noqa: BLE001 - the snow filter is a nicety
            logger.info("snow filter skipped: %s", exc)
    cand["_agency"] = (cand["area_source"] == "agency").astype(int) if "area_source" in cand.columns else 0
    cand = cand.sort_values(["_agency", "n_years"], ascending=[False, False])
    # spread across sources: round-robin over the per-source lists
    per = {s: g.to_dict("records") for s, g in cand.groupby("source", sort=False)}
    out: list[dict[str, Any]] = []
    while len(out) < n and any(per.values()):
        for s in list(per):
            if per[s]:
                r = per[s].pop(0)
                out.append({"source": r["source"], "station_id": r["station_id"], "area_km2": r.get("area_km2"),
                            "n_years": r.get("n_years"), "start": r.get("start"), "end": r.get("end"),
                            "q_mean_mm": r.get("q_mean_mm"), "runoff_ratio": r.get("runoff_ratio"),
                            "baseflow_index": r.get("baseflow_index"), "snow_cover_pct": r.get("snow_cover_pct")})
                if len(out) >= n:
                    break
    return out


def load_basin(
    source: str,
    station_id: str,
    *,
    start: date | str | None = None,
    end: date | str | None = None,
    area_km2: float | None = None,
    split: float | date | str = DEFAULT_SPLIT,
    cache_dir: str | Path | None = None,
    refresh: bool = False,
    catalog: list[dict[str, Any]] | None = None,
) -> Basin:
    """A real gauged basin from the Archive: discharge bundle (m3/s -> mm/d over the catchment area) plus
    Open-Meteo daily precipitation and FAO-56 ET0 at the gauge point (the Caravan exporter's forcing).

    Area: ``area_km2`` if given, else the station's catchment row (agency area, else BasinATLAS upstream
    area), else the catalog's ``extra.catchment_area_km2``. Cached as Parquet under the archive cache
    (``~/.cache/aquascope/archive/gym``) keyed by source, station and period. ``split`` is a fraction of
    the record or a date.
    """
    from aquascope.archive.bundles import load_observations, to_series
    from aquascope.archive.caravan import fetch_forcing
    from aquascope.archive.catalog import load_stations

    cat = catalog if catalog is not None else load_stations()
    st = next((r for r in cat if r["source"] == source and r["station_id"] == station_id), None)
    if st is None:
        raise KeyError(f"{source}/{station_id} is not in the Archive catalog")
    lat, lon = float(st["latitude"]), float(st["longitude"])
    area, area_source = area_km2, "given"
    if area is None:
        try:
            from aquascope.archive.similar import load_station_catchments

            tab = load_station_catchments()
            row = tab[(tab["source"] == source) & (tab["station_id"] == station_id)]
            if not row.empty and row.iloc[0].get("area_km2"):
                area, area_source = float(row.iloc[0]["area_km2"]), str(row.iloc[0].get("area_source") or "catchments")
        except Exception as exc:  # noqa: BLE001 - the table is optional
            logger.info("station catchments unavailable: %s", exc)
    if area is None:
        a = (st.get("extra") or {}).get("catchment_area_km2")
        if a:
            area, area_source = float(a), "agency"
    if not area or area <= 0:
        raise ValueError(f"no catchment area for {source}/{station_id}; pass area_km2=")

    cdir = _cache_dir(cache_dir)
    cdir.mkdir(parents=True, exist_ok=True)
    key = f"{source}__{station_id}__{start or 'auto'}__{end or 'auto'}".replace("/", "_")
    cached = cdir / f"{key}.parquet"
    if cached.exists() and not refresh:
        frame = pd.read_parquet(cached)
        meta = {"cached": True, "area_source": area_source}
    else:
        obs = load_observations(source, "discharge", station_ids=[station_id])
        if obs.empty:
            raise ValueError(f"the Archive has no discharge bundle rows for {source}/{station_id}")
        q = to_series(obs, station_id).dropna()
        q = q[q >= 0].resample("D").mean()
        t0 = pd.Timestamp(start) if start else q.first_valid_index()
        t1 = pd.Timestamp(end) if end else q.last_valid_index()
        t0 = max(t0, pd.Timestamp("1940-01-02"))  # ERA5 starts in 1940
        q = q.loc[t0:t1]
        forcing, model_used = fetch_forcing(lat, lon, t0.date(), t1.date())
        frame = pd.DataFrame({
            "precip": forcing["total_precipitation_sum"].to_numpy(dtype=float),
            "pet": forcing["potential_evaporation_sum_FAO_PENMAN_MONTEITH"].to_numpy(dtype=float),
        }, index=forcing.index)
        frame["q_obs"] = (q * 86.4 / area).reindex(frame.index)
        frame.to_parquet(cached)
        meta = {"cached": False, "area_source": area_source, "forcing_model": model_used}
    split_date = frame.index[int(len(frame) * float(split))] if isinstance(split, (int, float)) else pd.Timestamp(split)
    return Basin(id=f"{source}/{station_id}", name=st.get("name") or station_id, frame=frame, area_km2=float(area),
                 latitude=lat, longitude=lon, source=source, station_id=station_id, split_date=split_date,
                 meta={**meta, "agency": st.get("agency"), "license": st.get("license"),
                       "forcing": "Open-Meteo ERA5-Land/ERA5 blend at the gauge point (precip, FAO-56 ET0)"})


__all__ = ["Basin", "COLUMNS", "DEFAULT_SPLIT", "load_basin", "suggest_basins", "synthetic_basin"]
