"""Tests for the GR4J conceptual rainfall-runoff model."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest


def _make_forcing(n: int = 730, seed: int = 42) -> tuple[pd.Series, pd.Series]:
    """Create synthetic daily precipitation and PET series."""
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2018-01-01", periods=n, freq="D")

    # Precipitation: mostly dry days with occasional storms.
    storm = rng.choice([0, 0, 0, 0, 1], size=n)
    precip = pd.Series(storm * rng.exponential(8, n), index=idx, name="precip")

    # PET: smooth seasonal cycle (higher in summer), always positive.
    t = np.arange(n) / 365.25
    pet = pd.Series(2.5 + 2.0 * np.sin(2 * np.pi * t), index=idx, name="pet")
    pet = pet.clip(lower=0.2)

    return precip, pet


class TestGR4JSimulate:
    def test_returns_result(self):
        from aquascope.models.rainfall_runoff import GR4J

        precip, pet = _make_forcing()
        model = GR4J()
        result = model.simulate(precip, pet, warmup_days=30)
        assert len(result.streamflow) == len(precip)
        assert result.streamflow.index.equals(precip.index)

    def test_streamflow_non_negative(self):
        from aquascope.models.rainfall_runoff import GR4J

        precip, pet = _make_forcing()
        model = GR4J()
        result = model.simulate(precip, pet, warmup_days=30)
        assert (result.streamflow >= 0).all()

    def test_zero_precipitation_streamflow_decays(self):
        """With no rain at all, streamflow should trend toward zero as the
        initial routing-store water is depleted (recession behaviour)."""
        from aquascope.models.rainfall_runoff import GR4J

        idx = pd.date_range("2020-01-01", periods=200, freq="D")
        precip = pd.Series(0.0, index=idx)
        pet = pd.Series(3.0, index=idx)

        model = GR4J()
        result = model.simulate(precip, pet, warmup_days=0)
        # Streamflow in the last 20 days should be lower than in the first 20.
        assert result.streamflow.iloc[-20:].mean() < result.streamflow.iloc[:20].mean()

    def test_params_property_matches_constructor(self):
        from aquascope.models.rainfall_runoff import GR4J

        model = GR4J(x1=300.0, x2=1.0, x3=80.0, x4=2.0)
        assert model.params == {"X1": 300.0, "X2": 1.0, "X3": 80.0, "X4": 2.0}

    def test_unit_hydrographs_sum_to_one(self):
        from aquascope.models.rainfall_runoff import GR4J

        model = GR4J(x4=2.5)
        uh1, uh2 = model._unit_hydrographs()
        assert uh1.sum() == pytest.approx(1.0, abs=1e-6)
        assert uh2.sum() == pytest.approx(1.0, abs=1e-6)

    def test_higher_x1_increases_storage_capacity(self):
        """A larger production store should produce a smoother, lower-peak
        hydrograph for the same forcing (more storage to absorb rainfall)."""
        from aquascope.models.rainfall_runoff import GR4J

        precip, pet = _make_forcing()
        small_store = GR4J(x1=50.0).simulate(precip, pet, warmup_days=30)
        large_store = GR4J(x1=1000.0).simulate(precip, pet, warmup_days=30)
        assert large_store.streamflow.max() <= small_store.streamflow.max()


class TestGR4JCalibrate:
    def test_calibration_recovers_known_parameters(self):
        """Generate synthetic 'observed' discharge from a known parameter
        set, then check calibration finds a comparably-skilled fit."""
        from aquascope.models.rainfall_runoff import GR4J, calibrate

        precip, pet = _make_forcing(n=800)
        true_model = GR4J(x1=400.0, x2=0.5, x3=100.0, x4=2.0)
        observed = true_model.simulate(precip, pet, warmup_days=0).streamflow

        result = calibrate(
            precip, pet, observed,
            objective="kge", warmup_days=100, maxiter=15, seed=1,
        )
        # The objective should reflect a strong fit on data generated by
        # a GR4J model of the same structure.
        assert result.objective_value > 0.8

    def test_invalid_objective_raises(self):
        from aquascope.models.rainfall_runoff import calibrate

        precip, pet = _make_forcing(n=100)
        observed = pd.Series(np.zeros(100), index=precip.index)
        with pytest.raises(ValueError, match="Unknown objective"):
            calibrate(precip, pet, observed, objective="not_a_metric", maxiter=2)

    def test_result_params_within_bounds(self):
        from aquascope.models.rainfall_runoff import GR4J_PARAM_BOUNDS, calibrate

        precip, pet = _make_forcing(n=400)
        true_model_streamflow = pd.Series(
            np.abs(np.random.default_rng(0).normal(2, 1, 400)), index=precip.index
        )
        result = calibrate(precip, pet, true_model_streamflow, maxiter=5, seed=2)
        for key, (lo, hi) in GR4J_PARAM_BOUNDS.items():
            assert lo <= result.params[key] <= hi


def _reference_simulate(model, precip: pd.Series, pet: pd.Series) -> np.ndarray:
    """The original day-by-day formulation (buffer shifts with np.roll), kept as the parity oracle."""
    p = precip.values.astype(float)
    e = pet.values.astype(float)
    n = len(p)
    x1, x2, x3 = model.x1, model.x2, model.x3
    uh1, uh2 = model._unit_hydrographs()
    s, r = 0.3 * x1, 0.3 * x3
    uh1_state, uh2_state, out = np.zeros(len(uh1)), np.zeros(len(uh2)), np.zeros(n)
    for t in range(n):
        pn, en = model._net_rainfall_pet(p[t], e[t])
        if pn > 0:
            ps = model._production_store_input(pn, s, x1)
            s += ps
            perc_input = pn - ps
        else:
            s -= model._production_store_evap(en, s, x1)
            perc_input = 0.0
        perc = s * (1 - (1 + (4.0 / 9.0 * s / x1) ** 4) ** -0.25)
        s -= perc
        pr = perc + perc_input
        uh1_state = np.roll(uh1_state, -1)
        uh1_state[-1] = 0.0
        uh1_state += 0.9 * pr * uh1
        uh2_state = np.roll(uh2_state, -1)
        uh2_state[-1] = 0.0
        uh2_state += 0.1 * pr * uh2
        q9, q1 = uh1_state[0], uh2_state[0]
        exch = x2 * (r / x3) ** 3.5
        r = max(0.0, r + q9 + exch)
        qr = r * (1 - (1 + (r / x3) ** 4) ** -0.25)
        r -= qr
        out[t] = qr + max(0.0, q1 + exch)
    return out


@pytest.mark.parametrize("params", [
    dict(x1=320.0, x2=-0.8, x3=70.0, x4=2.1), dict(x1=1200.0, x2=3.0, x3=400.0, x4=0.6),
    dict(x1=50.0, x2=-8.0, x3=5.0, x4=9.7), dict(x1=1.0, x2=0.0, x3=1.0, x4=0.5),
])
def test_vectorised_simulate_matches_the_day_by_day_reference(params):
    """The convolution + two-scalar-loop simulate must reproduce the original buffer-shift loop to round-off."""
    from aquascope.models.rainfall_runoff import GR4J

    precip, pet = _make_forcing(1500, seed=7)
    model = GR4J(**params)
    new = model.simulate(precip, pet, warmup_days=0).streamflow.to_numpy()
    ref = _reference_simulate(model, precip, pet)
    assert np.max(np.abs(new - ref)) < 1e-10 * max(1.0, np.max(ref))
